### ISSUE TITLE
Wrong mod uploaded to this mod's SpaceDock

### ISSUE THREAD

**Issue by HebaruSan** [linuxgurugamer/BetterLoadSaveGame#4]
This just got uploaded to https://spacedock.info/mod/2326/Better%20Load%20Save%20Game%20Renewed :

![image](https://user-images.githubusercontent.com/1559108/75207050-9c179900-576f-11ea-82db-1084299019ee.png)

@linuxgurugamer

**Comment by linuxgurugamer** [comment]
Fixed, thank you
