### ISSUE TITLE
Frame rate impact

### ISSUE THREAD

**Issue by hngdog** [linuxgurugamer/BetterLoadSaveGame#5]
With about 30 other mods, medium graphics settings on a 10-year old Mac, I can get 30 fps in most operations, drops to about 24 on a huge merged space station.

With BetterLoadSaveGame installed (the 2.5.1 just out, and several earlier versions too) as the only mod difference, fps drops to 4 or 5 on even just a small probe either on surface or orbit or in map view.

No other changes at all.  1.9 KSP. 

F9 also brings up blank GUI with text piled up on top line, and a NullRef error, with message about GUIClips pushing more than popping. Kerbal Alarm clock puts its window inside the save window, which won't go away. Pressing F9 again doesn't just close the window, but also loads a save but not sure which one.

[KSP.log](https://github.com/linuxgurugamer/BetterLoadSaveGame/files/4252441/KSP.log)
![Screen Shot 2020-02-25 at 3 53 59 PM](https://user-images.githubusercontent.com/60797305/75292666-3fa58f80-57ea-11ea-8bdc-7a07f89ecd84.PNG)
![Screen Shot 2020-02-25 at 3 56 47 PM](https://user-images.githubusercontent.com/60797305/75292675-46cc9d80-57ea-11ea-9aae-d38f6f7986f6.PNG)

**Comment by linuxgurugamer** [comment]
Odd.  Looks like two different issues.
If you restart the game, will the KAC still appear in that window?

**Comment by linuxgurugamer** [comment]
Where did you install it from?

**Comment by linuxgurugamer** [comment]
What you are showing and describing looks like what I had in the middle of working on it.
I just installed it via CKAN, am not seeing what you are referring to.
It's quite possible that my system is too fast, I'm going to have to test on a different system.
I AM seeing the reloading after the 2nd F9, it is reloading the quicksave
I was not seeing anything impacting the frame rate

**Comment by linuxgurugamer** [comment]
Here is a test build.  This fixes the F9 issue, please try it out.  I ran a test on an older IMac (with Windows installed).  The framerate was unchanged regardless of if the mod is installed.

https://www.dropbox.com/s/862zei96rwsp3yf/BetterLoadSaveGame-2.5.1.1.zip?dl=0

I really need to know how you installed it, or, if by hand, where you got the file from.
Thanks

**Comment by hngdog** [comment]
Installed either from CKAN or your 'preview' on here, similar fps issues. GUI prob was no window at all in 2.4, glitched window like the included screen shot above, working, then back to glitched.
Been having frame rate issues for quite a while, finally traced it to this. GUI error is a bonus I guess. I cleared out all mods and started adding back in systematically. Scatterer and Kopernicus still a prob, so not using either right now.  SVT no longer needed for good terrain with the improvements to stock. EVE is a few FPS hit, but worth it. 

Just installed build you attached above.  GUI works with this build (it appears, and no errors anyway), but the saves don't sort, and are duplicated 4 times. See shots. Separate issue is the thumbnails are low pixel and missing the main ksp space scene.

But just this mod on or off has a huge fps impact.  Any other more detailed logging I can do?


![Screen Shot 2020-02-25 at 8 18 03 PM](https://user-images.githubusercontent.com/60797305/75305857-eac74080-580c-11ea-9d6d-721bd4405dba.PNG)
![Screen Shot 2020-02-25 at 8 18 15 PM](https://user-images.githubusercontent.com/60797305/75305859-ec910400-580c-11ea-9adc-5b7c98ae0d7e.PNG)
![Screen Shot 2020-02-25 at 8 18 23 PM](https://user-images.githubusercontent.com/60797305/75305860-ed299a80-580c-11ea-9a57-42b8c44dc23f.PNG)
![Screen Shot 2020-02-25 at 8 18 34 PM](https://user-images.githubusercontent.com/60797305/75305864-ed299a80-580c-11ea-9481-ebc4636988e7.PNG)
![Screen Shot 2020-02-25 at 8 18 45 PM](https://user-images.githubusercontent.com/60797305/75305866-edc23100-580c-11ea-93a9-4b2a9fce807e.PNG)
![Screen Shot 2020-02-25 at 8 19 31 PM](https://user-images.githubusercontent.com/60797305/75305867-ee5ac780-580c-11ea-81a3-0c5bef688564.PNG)

Note 29 FPS on this without.
![Screen Shot 2020-02-25 at 8 28 56 PM](https://user-images.githubusercontent.com/60797305/75306459-c2404600-580e-11ea-884d-897fecff9197.PNG)

**Comment by linuxgurugamer** [comment]
I see it, but have no idea right now what's going on.
The only thing I see  different is that you are running OSX, and I'm testing it on Windows.
I have a Mac from work, will see if I can do some testing there.
What are you using to get the FPS?
Can you take a screenshot of the save directory and post it, please?

I'm going to see if I can add more logging, until then, I'd suggest not using it

**Comment by linuxgurugamer** [comment]
Just an FYI, I have replicated the problem on a mac, will need to figure out what's going on.
Edit:  All the problems have been replicated.

**Comment by hngdog** [comment]
Using Steam overlay for FPS.
It's a long career game. Maybe that's a problem? 420 saves. Let me try in a much newer sandbox save.
[list of saves.txt](https://github.com/linuxgurugamer/BetterLoadSaveGame/files/4253606/list.of.saves.txt)

**Comment by linuxgurugamer** [comment]
Ok, that list helps.  I'll look at it this evening, thanks
I still don't know what's causing the framerate drop

**Comment by linuxgurugamer** [comment]
Just released a fix, 2.5.1.1.  In my test where the framerate was dropping to 5, it now stays at 15 (15 without and with)

**Comment by hngdog** [comment]
Installed from CKAN and then direct download. My frame rate is back in the teens to 20s, so much better. 
But still getting this: (Steam did just install 1.9.1 if that matters...) 
Large career and small sandbox game with only a few saves shows same GUI error.

![Screen Shot 2020-02-27 at 10 58 01 PM](https://user-images.githubusercontent.com/60797305/75511808-f190b780-59b4-11ea-8e37-7525fc94ee77.PNG)

**Comment by linuxgurugamer** [comment]
You are in the mapview, does it happen in flight view and/or space center?
Also, an updated log file, please

**Comment by linuxgurugamer** [comment]
I've been able to replicate it, no need for a log file.
I've also seen the multiple copies of the same save file, I suspect these are related

**Comment by linuxgurugamer** [comment]
Just so you know, this is intermittent.  In my testing, it works about 1/3 of the time

**Comment by linuxgurugamer** [comment]
Gaah, I'm kicking myself.
This was the exact same problem, except in a different section of code.  Fixed, tested and released.

**Comment by hngdog** [comment]
Thanks for your persistence!
