### ISSUE TITLE
Enhancement/change — why show 'Persistent' save?

### ISSUE THREAD

**Issue by hngdog** [linuxgurugamer/BetterLoadSaveGame#6]
Isn't the Persistent always up to date?

Like, NOW? Why or even how would I need to reload, Now?

Sure, it's a save file. But I have to load it to tell the game which player I am anyway, and then it updates as I play, and saves itself as the final thing when I quit.  When else would I ever need it?

Seems like it doesn't need to be shown at all.  Autosaves and quick saves are already there.
Plus I don't think it creates the thumbnail on a continuous basis anyway. On mine, the persistent save shows a GUI overlay but no scene.

**Comment by linuxgurugamer** [comment]
Please confirm that the screenshot is not updated when doing a new save, if so, then it's a bug

**Comment by linuxgurugamer** [comment]
An option to hide the persistent.sfs will be in the next release, this was pretty easy to do

**Comment by linuxgurugamer** [comment]
Just so you know, the persistant.sfs only gets updated on scene changes.  So if you are in a scene for a long time (ie:  flight) and you want to revert to the last time you entered the scene, you would use the persistant.sfs
